R 语言之所以能作为统计计算的利器，是因为它可以比较方便地生成特定随机分布，比如正态分布。以下代码都属于 R 里正态分布相关函数的用法。

R 对很多概率分布都提供了统一命名规则：

d*：density，密度函数

p*：distribution，分布函数

q*：quantile，分位数函数

r*：random，随机抽样

值得注意的是，R语言中的正态分布相关函数的参数填入是均值和标准差，而非是一般课本上的均值与方差。

In [ ]:
dnorm(4, 2, sqrt(4))    # 在某一点的概率密度
pnorm(4, 2, sqrt(4))    # 在某一点对应的概率分布值

alpha <- 0.05
qnorm(1 - alpha / 2, 0, 1)  # 求对应概率的分位点

rnorm(20, 0, 1)       # 从正态分布中随机取样，这里就生成20个了。

[1] 0.1209854

[1] 0.8413447

[1] 1.959964

[1]  0.4875087 -1.4311183 -0.9389959  0.6474586  0.6590592  0.1457390
 [7]  0.2673607 -0.3942277  0.3352562  0.5949548 -1.5008227 -1.7346799
[13] -1.1723540 -0.6299970  0.2590633 -0.6418819  1.3321510 -0.9436843
[19] -0.3846993  0.7315297

一些向量相关的函数。

In [1]:
vector(mode = "logical", length = 0)
x <- 1:3
as.vector(x, mode = "any")
print(is.vector(x, mode = "any"))
print(x[2])

logical(0)

[1] 1 2 3

[1] TRUE
[1] 2


讨论完向量着这种数据结构后，接下来我们来讨论矩阵的运算。可以看出，R 可以将向量转为矩阵，默认是按照列进行，如果要按照行展开，需要附加参数。

In [8]:
print(matrix(data = 5, nr = 2, nc = 2))
print(matrix(1:6, 2, 3))
print(matrix(1:6, 2, 3, byrow = TRUE))

x <- 1:6
# 给 x 附加上维度信息，指定为2行3列
dim(x) <- c(2, 3)
print(x)
# 取出矩阵中指定的元素
print(x[1, 2])
print(x[, 3])
print(x[2, ])


     [,1] [,2]
[1,]    5    5
[2,]    5    5


     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6
[1] 3
[1] 5 6
[1] 2 4 6


讨论完矩阵后，接下来我们依次讨论数据框，array 和 list。我们着重说一下 array 和 list 的区别，array 是同一种数据类型构成的多维数据结构，它可以有很多个维度；而 list 是可以存放不同类型对象的容器，它和向量不同，list 里的每个元素都可以完全不一样。

In [ ]:
# data.frame 相关的代码
df <- data.frame(
  Name = c("Alice", "Becka", "James", "Jeffrey", "John"),
  Sex = c("F", "F", "M", "M", "M"),
  Age = c(13, 13, 12, 13, 12),
  Height = c(56.5, 65.3, 57.3, 62.5, 59.0),
  Weight = c(84.0, 98.0, 83.0, 84.0, 99.5)
)
print(df)

print(df$Weight)
print(df$Age)

     Name Sex Age Height Weight
1   Alice   F  13   56.5   84.0
2   Becka   F  13   65.3   98.0
3   James   M  12   57.3   83.0
4 Jeffrey   M  13   62.5   84.0
5    John   M  12   59.0   99.5
[1] 84.0 98.0 83.0 84.0 99.5
[1] 13 13 12 13 12


In [15]:
# array 和 list
x <- array(1:12, dim = c(2, 3, 2))
print(x)
print(x[1, , ])

x <- list(1:3, "hello", TRUE)
print(x)

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

     [,1] [,2]
[1,]    1    7
[2,]    3    9
[3,]    5   11
[[1]]
[1] 1 2 3

[[2]]
[1] "hello"

[[3]]
[1] TRUE



有的时候，我们并不希望表达式直接计算出结果，而是希望能直接把表达式存入，可以做到随调随用。要实现这一功能，我们就需要引入 R 语言的 expression 了。

In [17]:
exp1 <- expression(x / (y + exp(z)))    # 构建表达式，不求值
print(exp1)
x <- 3; y <- 2.5; z <- 1    # 给变量赋值
print(eval(exp1))   # 求值

expression(x/(y + exp(z)))
[1] 0.5749019


R 中特有的数据结构我们已经初步介绍完了，接下来介绍的是 R 中的基本运算包括算术运算和逻辑运算等。算术运算具体可以列表如下：
| 运算符 | 含义 | 示例 | 结果 |
|---|---|---|---|
| `+` | 加法 | `3 + 2` | `5` |
| `-` | 减法 | `3 - 2` | `1` |
| `*` | 乘法 | `3 * 2` | `6` |
| `/` | 除法 | `3 / 2` | `1.5` |
| `^` | 乘方 | `3 ^ 2` | `9` |
| `%%` | 取余 | `7 %% 3` | `1` |
| `%/%` | 整除 | `7 %/% 3` | `2` |

In [1]:
print(3 + 2)
print(3 / 2)
print(7 %% 3)

[1] 5
[1] 1.5
[1] 1


逻辑运算具体可以列表如下：
| 运算符    | 含义           | 示例                                   | 结果      |
| ------ | ------------ | ------------------------------------ | ------- |
| `&`    | 逐元素“与”       | `TRUE & FALSE`                       | `FALSE` |
| `\|`   | 逐元素“或”       | `TRUE \| FALSE`                      | `TRUE`  |
| `!`    | 逻辑非          | `!TRUE`                              | `FALSE` |
| `&&`   | 只比较第一个元素的“与” | `c(TRUE, FALSE) && c(TRUE, TRUE)`    | `TRUE`  |
| `\|\|` | 只比较第一个元素的“或” | `c(FALSE, TRUE) \|\| c(TRUE, FALSE)` | `TRUE`  |

值得注意的是，R 语言实现了对异或运算的支持，具体如下。


In [ ]:
print(xor(TRUE, FALSE))

[1] TRUE


比较运算具体可以列表如下：
| 运算符  | 含义   | 示例       | 结果      |
| ---- | ---- | -------- | ------- |
| `>`  | 大于   | `5 > 3`  | `TRUE`  |
| `<`  | 小于   | `5 < 3`  | `FALSE` |
| `>=` | 大于等于 | `5 >= 5` | `TRUE`  |
| `<=` | 小于等于 | `3 <= 2` | `FALSE` |
| `==` | 等于   | `4 == 4` | `TRUE`  |
| `!=` | 不等于  | `4 != 5` | `TRUE`  |

这里就不具体给出示例代码了，读者自写不难。接下来是对一些字符串的操作，举一些例子进行理解。

In [3]:
colors <- c("red", "yellow", "blue")
print(colors)
more_colors <- c(colors, "green", "magenta", "cyan")
print(more_colors)

substr(colors, 1, 2)

paste(colors, "flowers")
paste("several ", colors, "s", sep = "")
paste("I like", colors, collapse = ", ")

[1] "red"    "yellow" "blue"  
[1] "red"     "yellow"  "blue"    "green"   "magenta" "cyan"   


[1] "re" "ye" "bl"

[1] "red flowers"    "yellow flowers" "blue flowers"

[1] "several reds"    "several yellows" "several blues"

[1] "I like red, I like yellow, I like blue"

显然，```substr()``` 是截取字符串的某一部分，```paste()``` 是拼接字符串。